// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsSharp.Data;

namespace TsSharp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190612112751_initil")]
    partial class initil
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TsSharp.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatId");

                    b.Property<string>("Desc");

                    b.Property<string>("FotoName");

                    b.Property<string>("FullDesc");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("TsSharp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatId");

                    b.Property<string>("Desc");

                    b.Property<string>("FotoMin");

                    b.Property<string>("FotoName");

                    b.Property<string>("FullDesc");

                    b.Property<bool>("IsSpecial");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TsSharp.Models.Prop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc");

                    b.Property<string>("FotoName");

                    b.Property<string>("FullDesc");

                    b.Property<bool>("IsFilter");

                    b.Property<string>("Name");

                    b.Property<int?>("ProductId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Props");
                });

            modelBuilder.Entity("TsSharp.Models.Cat", b =>
                {
                    b.HasOne("TsSharp.Models.Cat")
                        .WithMany("Cats")
                        .HasForeignKey("CatId");
                });

            modelBuilder.Entity("TsSharp.Models.Product", b =>
                {
                    b.HasOne("TsSharp.Models.Cat")
                        .WithMany("Products")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TsSharp.Models.Prop", b =>
                {
                    b.HasOne("TsSharp.Models.Product")
                        .WithMany("Props")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
